add explanation on what the bb_runner container situation is about
buildbarn/bb-remote-execution pull request #124
Opened 2024-02-01 16:10 UTC by lucasmeijer

Add more information about why there are two bb_runner container images, and when and how to use them.

2024-02-01 16:11 UTC, EdSchouten reviewed
LGTM, but can you please wrap sentences at <80 columns for consistency with the rest of the document?

2024-02-01 16:31 UTC, EdSchouten approved these changes

2024-02-01 20:18 UTC, moroten requested changes
Excellent. Just a few nit picks.

2024-02-01 20:18 UTC, moroten commented on README.md
> +This  is where `bb_runner_installer` image comes in. It doesn't actually
```suggestion
This is where `bb_runner_installer` image comes in. It doesn't actually
```

2024-02-01 20:18 UTC, moroten commented on README.md
> +in the [docker-compose example](https://github.com/buildbarn/bb-deployments/blob/e404c1a519355353d0e2cdfd447126fe07095594/docker-compose/docker-compose.yml#L89)
```suggestion
in the [docker-compose example](https://github.com/buildbarn/bb-deployments/blob/e404c1a519355353d0e2cdfd447126fe07095594/docker-compose/docker-compose.yml#L89).
```

2024-02-01 20:18 UTC, moroten commented on README.md
> +executable from buildbarn's provided container. There's a few tricks to check
```suggestion
executable from Buildbarn's provided container. There's a few tricks to check
```

2024-02-01 20:18 UTC, moroten commented on README.md
> +`bb_runner_bare` has no userland/linux install, it just has the bb_runner
```suggestion
`bb_runner_bare` has no userland/linux install, it just has the `bb_runner`
```

2024-02-01 21:34 UTC, moroten approved these changes

2024-02-02 05:33 UTC, merged

2024-02-02 09:11 UTC, stagnation commented
Great thank you!